# Generated by Django 6.0.2 on 2026-02-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_barbeiros_location_servicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='duracao_minutos',
            field=models.PositiveIntegerField(choices=[(15, '15 min'), (30, '30 min'), (60, '60 min')], default=30),
        ),
    ]
