# Generated by Django 6.0.2 on 2026-02-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_servicos_duracao_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.barbeiros')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.servicos')),
            ],
        ),
    ]
