# Generated by Django 6.0.2 on 2026-02-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_agendamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='codigo_redf',
            field=models.IntegerField(default=0),
        ),
    ]
