# Generated by Django 6.0.2 on 2026-02-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_usuarios_codigo_redf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('inicio_manha', models.TimeField(blank=True, null=True)),
                ('fim_manha', models.TimeField(blank=True, null=True)),
                ('inicio_tarde', models.TimeField(blank=True, null=True)),
                ('fim_tarde', models.TimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
