# Generated by Django 6.0.2 on 2026-02-06 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usuarios'),
        ),
    ]
