# Generated by Django 6.0.2 on 2026-02-06 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_agendamentos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='e_barbeiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nome_barbeiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.barbeiros'),
        ),
    ]
