# Generated by Django 6.0.2 on 2026-02-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usuarios_e_barbeiro_usuarios_nome_barbeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
